kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
  namespace: cp4ba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cp4ba/nfs-client					# you can change this name to what your own chosen name
            - name: NFS_SERVER
              value: <NFSSERVER>		# change to a real NFS server name
            - name: NFS_PATH
              value: /data/nfsshare/logs							# adjust as needed
      volumes:
        - name: nfs-client-root
          nfs:
            server: <NFSSERVER>		# chnage to a real NFS server name
            path: /data/nfsshare/logs							# adjust as needed
